version: '3.3'

services:

  transmission:
    container_name: transmission
    hostname: transmission
    image: linuxserver/transmission
    restart: always
    ports:
      - 9091:9091/tcp
      - 51413:51413/tcp
      - 51413:51413/udp
    volumes:
      - /home/artur/smarthome/torrent/transmission-config:/config
      - /mnt/share:/downloads
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Moscow
      - transmission_download-dir=/downloads/torrent
      - transmission_incomplete-dir=/downloads/temp
      - transmission_watch-dir=/downloads/watch

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./sonarr:/config
      - /mnt/share/serials:/serials
      - /mnt/share:/downloads
    ports:
      - 8989:8989
    restart: always

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - TZ=Europe/Moscow
      - PUID=1000
      - PGID=1000
    volumes:
      - ./radarr:/config
      - /mnt/share/films:/movies
      - /mnt/share:/downloads
    ports:
      - 7878:7878
    restart: always

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./jackett:/config
    ports:
      - 9117:9117
    restart: always

  torproxy:
    restart: always
    image: dperson/torproxy:latest
    container_name: torproxy

  gramarrru:
    image: memodota/gramarrru
    container_name: gramarrru
    depends_on:
      - sonarr
      - radarr
    volumes:
      - ./gramarr:/config
    restart: unless-stopped
